services:
  - type: web
    name: cuenteria-sound-board
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
